config/routes.rb
Rails.application.routes.draw do
  root "orders#index"  
  resources :orders do
    resources :lines
    resources :archived_lines
  end
  resources :archived_orders
  resources :stocks
  resources :products
end

app/models/decimal_place_validator.rb
class DecimalPlaceValidator < ActiveModel::Validator
  def validate product
    decimals = product.price.to_s.split('.')
    if decimals.size == 2 && decimals.last.size > 2
      product.errors.add(:price, "can't be more than 2 decimal places")
    end
  end
end

app/models/in_stock_validator.rb
class InStockValidator < ActiveModel::Validator
  def validate record
    product = record.product
    unless product.stock_level >= 0
      record
        .errors[:quantity] << "is too large - #{product.stock_level} in stock"
    end
  end
end

app/models/line.rb
class Line < ActiveRecord::Base
  belongs_to :order
  belongs_to :product

  validates :product_id, presence: true
  validates(:quantity, presence: true, numericality: { only_integer: true })

  validates_with InStockValidator

  after_initialize :init

  def init
    self.archived ||= false
  end

  def possible_products
    current_product_ids = order.unarchived_lines.pluck(:product_id)
    Product.where.not(id: current_product_ids).in_stock
  end

  def name
    product.name
  end

  def total_price
    product.price * quantity
  end

  def formatted_price
    "#{product.price} (#{total_price})"
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :lines
  after_initialize :init

  validates_with StatusValidator
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :status, presence: true
  validates :address_line_1, presence: true
  validates :postcode, presence: true


  def self.unarchived
    where(archived: false).order(created_at: :desc)
  end

  def self.archived
    where(archived: true).order(created_at: :desc)
  end

  def self.format_time time
    time.strftime("%m/%e/%y %H:%M")
  end

  def init
    self.archived ||= false
    self.status ||= "pending"
  end

  def unarchived_lines
    lines.where(archived: false)
  end

  def archived_lines
    lines.where(archived: true)
  end

  def name
    [first_name, last_name].compact.join " "
  end

  def truncated_address
    addresses = [address_line_1, address_line_2, address_line_3].join ", "
    addresses[0..15] + "..."
  end

  def including
    including_line = unarchived_lines.map(&:name).join(", ")
    including_line.length > 15 ? including_line[0..15] + "..." : including_line
  end

  def available_statuses status_override=nil
    if status_override != nil
      current_status = status_override
    else
      current_status = status
    end
    return ["confirmed", "dispatched"] if current_status == "confirmed"
    return ["pending", "confirmed"] if current_status == "pending"
    return ["pending"]
  end

  def total_price
    unarchived_lines.map(&:total_price).inject(0, :+)
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :lines
  has_many :stocks

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { precision: 2 }

  validates_with DecimalPlaceValidator

  def self.in_stock
    all.select { |p|
      p.stock_level > 0
    }
  end

  def unarchived_lines
    lines.where(archived: false)
  end

  def short_description
    description.length > 20 ? description[0...20] + "..." : description
  end

  def stock_level
    total_ordered = unarchived_lines
      .pluck(:quantity)
      .inject(0, &:+)
    total_stocked = stocks
      .pluck(:amount)
      .inject(0, &:+)
    total_stocked - total_ordered
  end
end

app/models/status_validator.rb
class StatusValidator < ActiveModel::Validator
  def validate order
    unless order
      .available_statuses(order.status_was)
      .include? order.status
      order.errors[:status] << 
        "cannot be moved from #{order.status_was} \
         to order.status"
    end
  end
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/archived_lines_controller.rb
class ArchivedLinesController < ApplicationController
  def index
    @order = Order.find(params[:order_id])
    @lines = @order.archived_lines
  end
end

app/controllers/archived_orders_controller.rb
class ArchivedOrdersController < ApplicationController
  def index
    @orders = Order.archived
  end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  def new
    @order = Order.find(params[:order_id])
    @line = Line.new
    @line.order = @order
  end

  def edit
    @order = Order.find(params[:order_id])
    @line = Line.find(params[:id])
  end

  def create
    @order = Order.find(params[:order_id])
    @line = Line.new(line_params)
    @line.order = @order
    if @line.save
      redirect_to @order
    else
      render :new
    end
  end

  def destroy
    @order = Order.find(params[:order_id])
    @line = Line.find(params[:id])
    @line.destroy
    if @line.archived == true
      redirect_to url_for(@order) + "/archived_lines"
    else
      redirect_to @order
    end
  end

  def update
    @order = Order.find(params[:order_id])
    @line = Line.find(params[:id])
    @line.update(line_params)
    redirect_to @order
  end

  private
  def line_params
    params.require(:line).permit(:quantity, :product_id, :archived)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
  end

  def edit
    @order = Order.find(params[:id])
  end
  
  def destroy
    @order = Order.find(params[:id])
    @order.lines.each { |l| l.destroy }
    @order.destroy
    redirect_to :archived_orders
  end

  def index
    @archived_orders = Order.archived
    @pending_orders = Order.unarchived.where(status: "pending")
    @confirmed_orders = Order.unarchived.where(status: "confirmed")
    @dispatched_orders = Order.unarchived.where(status: "dispatched")
    @orders = [@pending_orders, @confirmed_orders, @dispatched_orders].select do |group|
      !group.empty?
    end
  end

  def create
    @order = Order.new order_params
    if @order.save
      redirect_to @order
    else
      render :new
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      if @order.archived == true
        redirect_to :orders
      else
        redirect_to @order
      end
    else
      render :edit
    end
  end

  private
  def order_params
    params.require(:order).permit(
      :first_name,
      :last_name,
      :address_line_1, :address_line_2, :address_line_3,
      :postcode,
      :status,
      :archived)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to "/stocks"
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price)
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
    @products = Product.all
    @stock = @products.map do |product|
      { 
        details: product, 
        quantity: product.stock_level
      }
    end
  end  
  
  def new
    @products = Product.all
    @stock = Stock.new
  end
  
  def show
    @stock = Stock.find(params[:id])
  end
  
  def create
    @product = Product.find(params[:stock][:product_id])
    @stock = Stock.new(stock_params)
    @stock.product = @product
    
    if @stock.save
      redirect_to "/stocks"
    else
      render :new
    end
  end
  
  private
  def stock_params
    params.require(:stock).permit(:amount, :product_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/archived_lines/index.html.erb
<%= link_to "back to order", @order, class: "btn btn-info btn-main-menu" %>
<h1>archived order lines</h1>
<br/>
<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th class="col-md-6">product name</th>
      <th class="col-md-2">quantity</th>
      <th class="col-md-4" colspan="2">actions</th>
    </tr>
  </thead>
  <tbody>
    <% @lines.each do |line| %>
      <tr>
        <td><%= line.product.name %></td>
        <td><%= line.quantity %></td>
        <td>
          <form action="<%= order_line_path(@order, line) %>" method="post">
            <input type="hidden" name="_method" value="patch"/>
            <input type="hidden" name="line[archived]" value="false"/>
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
            <input type="submit" value="restore <%= line.name %>" class="btn btn-primary btn-small"/>
          </form>
        </td>
        <td>
          <form action="<%= order_line_path(@order, line) %>" method="post">
            <input type="hidden" name="_method" value="delete"/>
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
            <input type="submit" value="permanently delete <%= line.name %>" class="btn btn-danger btn-small"/>
          </form>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/archived_orders/index.html.erb
<%= link_to "all orders", orders_path, class: "btn btn-info btn-main-menu" %>
<h1>archived orders</h1>
<table class="table table-striped table-hover table-bordered">
  <tr>
    <th class="col-md-2">order for</th>
    <th class="col-md-3">address...</th>
    <th class="col-md-2">postcode</th>
    <th class="col-md-3">including...</th>
    <th class="col-md-2" colspan=2>actions</th>
  </tr>
  <% @orders.each do |order| %>
    <tr>
      <td><a href="<%= url_for(order) %>"><%= order.name %>             </a></td>
      <td><a href="<%= url_for(order) %>"><%= order.truncated_address %></a></td>
      <td><a href="<%= url_for(order) %>"><%= order.postcode %>         </a></td>
      <td><a href="<%= url_for(order) %>"><%= order.including %>        </a></td>
      <td><form action="<%= order_path(order) %>" method="post">
        <input type="hidden" name="_method" value="patch"/>
        <input type="hidden" name="order[archived]" value="false"/>
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
        <input type="submit" value="restore" class="btn btn-primary btn-small"/>
      </form></td>
      <td><form action="<%= order_path(order) %>" method="post">
        <input type="hidden" name="_method" value="delete"/>
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
        <input type="submit" value="delete <%= order.name %>'s order" class="btn btn-danger btn-small"/>
      </form></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="A web app for orchestrating the order of musical instruments">
  <meta name="author" content="Duncan Fermor">
  <title>orchestrate</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="watermark">
  </div>
  <div class="container">
  <hr/>
    <%= yield %>
  </div>
  
</body>
</html>

app/views/lines/edit.html.erb
<%= link_to "back to order", order_path(@order), class: "btn btn-info btn-main-menu" %>
<br/>
<br/>
<%= simple_form_for [@order, @line] do |f| %>
  <%= f.input :product_id, label: "product", :collection => @line.possible_products + [@line.product], :as => :select, :include_blank => false %>
  <%= f.input :quantity, label: "quantity" %>
  <%= f.button :submit, value: "save", class: "btn btn-primary" %>
  <%= link_to "cancel", order_path(@order), class: "btn btn-info" %>
<% end %>

app/views/lines/new.html.erb
<%= link_to "back to order", order_path(@order), class: "btn btn-info btn-main-menu" %>
<br/>
<h1>new order line</h1>
<br/>
<%= simple_form_for [@order, @line] do |f| %>
  <%= f.input :product_id, label: "product", :collection => @line.possible_products, :as => :select%>
  <%= f.input :quantity, label: "quantity" %>
  <%= f.button :submit, value: "add", class: "btn btn-primary" %>
  <%= link_to "cancel", order_path(@order), class: "btn btn-info" %>
<% end %>

app/views/orders/edit.html.erb
<%= link_to "back to order", order_path(@order), class: "btn btn-info btn-main-menu" %>
<h2>edit order</h2>
<%= simple_form_for @order do |f| %>
  <%= f.input :first_name, label: "first name" %>
  <%= f.input :last_name, label: "last name" %>
  <%= f.input :status, label: "status", collection: @order.available_statuses, :include_blank => false %>

  <fieldset class="form-group">
    <legend>address</legend>
    <div class="indent20">
      <%= f.input :address_line_1, label: "line 1" %>
      <%= f.input :address_line_2, label: "line 2" %>
      <%= f.input :address_line_3, label: "line 3" %>
      <%= f.input :postcode, label: "postcode" %>
    </div>
  </fieldset>
  <%= f.button :submit, value: "update", class: "btn btn-primary" %>
  <%= link_to "cancel", order_path(@order), class: "btn btn-info" %>
<% end %>

app/views/orders/index.html.erb
<%= link_to "stock", "/stocks", class: "btn btn-info btn-main-menu" %>
<% if @archived_orders.length > 0 %>
  <%= link_to "archived orders", archived_orders_path, class: "btn btn-warning btn-main-menu" %>
<% end %>
<hr/>
<h1>orders</h1>
<br/>
<%= link_to "create", new_order_path, class: "btn btn-primary" %>
<% @orders.each do |order_group| %>
  <h2><%= order_group[0].status %></h2>
  <br/>
  <table class="table table-striped table-bordered">
    <tr>
      <th class="col-md-2">date</th>
      <th class="col-md-2">order for</th>
      <th class="col-md-2">address...</th>
      <th class="col-md-2">postcode</th>
      <th class="col-md-2">including...</th>
      <th class="col-md-2">actions</th>
    </tr>
    <% order_group.each do |order| %>
      <tr>
        <td><a href="<%= url_for(order) %>"><%= Order.format_time(order.created_at)%></a></td>
        <td><a href="<%= url_for(order) %>"><%= order.name %>             </a></td>
        <td><a href="<%= url_for(order) %>"><%= order.truncated_address %></a></td>
        <td><a href="<%= url_for(order) %>"><%= order.postcode %>         </a></td>
        <td><a href="<%= url_for(order) %>"><%= order.including %>        </a></td>
        <td><form action="<%= order_path(order) %>" method="post">
          <input type="hidden" name="_method" value="patch"/>
          <input type="hidden" name="order[archived]" value="true"/>
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
          <input type="submit" value="archive <%= order.name %>'s order" class="btn btn-danger btn-small"/>
        </form></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/orders/new.html.erb
<%= link_to "back to orders", "/orders", class: "btn btn-info btn-main-menu" %>
<h1>new order</h1>
<%= simple_form_for @order do |f| %>
  <%= f.input :first_name, label: "first name" %>
  <%= f.input :last_name, label: "last name" %>
  <fieldset class="form-group">
    <legend>address</legend>
    <div class="indent20">
      <%= f.input :address_line_1, label: "line 1" %>
      <%= f.input :address_line_2, label: "line 2" %>
      <%= f.input :address_line_3, label: "line 3" %>
      <%= f.input :postcode, label: "postcode" %>
    </div>
  </fieldset>
  <%= f.button :submit, value: "create order", class: "btn btn-primary" %>
  <%= link_to "cancel", "/orders", class: "btn btn-info" %>
<% end %>

app/views/orders/show.html.erb
<%= link_to "all orders", orders_path, class: "btn btn-info btn-main-menu" %>
<h1>order for: <%= @order.name %></h1>
<div>
  <h3><%= @order.status %></h3>
  <h3>address:</h3>
  <p class="indent20">
    <%= @order.address_line_1 %><br/>
    <%= @order.address_line_2 %><br/>
    <%= @order.address_line_3 %>
    <%= @order.postcode %>
  </p>
</div>
<hr/>
<div>
  <%= link_to "edit order", edit_order_path(@order), class: "btn btn-info" %>
  <%= link_to "add product", new_order_line_path(@order), class: "btn btn-success" %>
  <% if @order.archived_lines.length > 0 %>
    <%= link_to "show archived", order_archived_lines_path(@order), class: "btn btn-warning" %>
  <% end %>
</div>
<hr/>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th class="col-md-4">product name</th>
      <th class="col-md-2">quantity</th>
      <th class="col-md-2">price</th>
      <th class="col-md-4" colspan="2">actions</th>
    </tr>
  </thead>
  <tbody>
    <% @order.unarchived_lines.each do |line| %>
    <tr>
      <td><%= line.product.name %></td>
      <td><%= line.quantity %></td>
      <td><%= line.formatted_price %></td>
      <td><%= link_to "edit", edit_order_line_path(@order, line), class: "btn btn-info btn-small" %></td>
      <td>
        <form action="<%= order_line_path(@order, line) %>" method="post">
          <input type="hidden" name="_method" value="patch"/>
          <input type="hidden" name="line[archived]" value="true"/>
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
          <input type="submit" value="archive <%= line.name %>" class="btn btn-danger btn-small"/>
        </form>
      </td>
    </tr>
    <% end %>
    <tr>
      <td colspan="2"></td>
      <td><%= @order.total_price %></td>
      <td colspan="2"></td>
    </tr>
  </tbody>
</table>

app/views/products/new.html.erb
<%= link_to "back to stock", "/stocks", class: "btn btn-info btn-main-menu" %>
<h2>new product line</h2>
<%= simple_form_for @product do |f| %>
  <%= f.input :name, label: "name" %>
  <%= f.input :price, label: "price" %>
  <%= f.input :description, label: "description" %>
  <%= f.button :submit, value: "add product", class: "btn btn-primary" %>
  <%= link_to "cancel", "/stocks", class: "btn btn-info" %>
<% end %>

app/views/products/show.html.erb
<%= link_to "all stock", stocks_path, class: "btn btn-info" %>
<h2><%= @product.name %></h2>
<div>
  <p><%= @product.description %></p>
</div>
<hr/>

app/views/stock/index.html.erb
<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th class="col-md-4">name</th>
      <th class="col-md-6">description</th>
      <th class="col-md-2">quantity</th>
    </tr>
  </thead>
  <tbody>
    <% @stock.each do |s| %>
    <tr>
      <td><%= s[:details].name %></td>
      <td><%= s[:details].short_description %></td>
      <td><%= s[:quantity] %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/stocks/index.html.erb
<%= link_to "orders", "orders", class: "btn btn-info btn-main-menu" %>
<hr/>
<h1>stock</h1>
<br/>
<%= link_to "add/remove stock", new_stock_path, class: "btn btn-primary" %>
<%= link_to "new product line", new_product_path, class: "btn btn-info" %>
<br/>
<br/>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th class="col-md-4">name</th>
      <th class="col-md-4">description</th>
      <th class="col-md-2">quantity</th>
      <th class="col-md-2">price</th>
    </tr>
  </thead>
  <tbody>
    <% @stock.each do |s| %>
    <tr>
      <td><%= link_to s[:details].name, s[:details]%></td>
      <td><%= link_to s[:details].short_description, s[:details] %></td>
      <td><%= link_to s[:quantity], s[:details] %></td>
      <td><%= link_to s[:details].price, s[:details] %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/stocks/new.html.erb
<%= link_to "back to stock", "/stocks", class: "btn btn-info btn-main-menu" %>
<h2>new stock update</h2>
<%= simple_form_for @stock do |f| %>
  <%= f.input :product_id, label: "product", collection: @products %>
  <%= f.input :amount, label: "amount", hint: "to reduce stock levels, input a negative number" %>
  <%= f.button :submit, value: "add/remove stock", class: "btn btn-primary" %>
  <%= link_to "cancel", "/stocks", class: "btn btn-info" %>
<% end %>